### ISSUE TITLE
Not an issue: Can you do this for the "this is fine" meme? 

### ISSUE THREAD

**Issue by mickeyboxell** [mackorone/tidbyt-nyan-cat#1]
I'm not sure of the best way to make a suggestion for your next project, but I would love to see a similar Tidbyt app for the "this is fine" meme: https://giphy.com/gifs/perfect-loops-kspVl6FzbdblOMKRmM. I would have written it myself, but then I saw your work using Pixilart to make the frames and got intimidated :)

**Comment by mackorone** [comment]
> best way to make a suggestion for your next project

This is fine (pun intended).

I'll add it to my TODO list, but no promises it gets done soon, if ever.

**Comment by mackorone** [comment]
@mickeyboxell, as it turns out, you can just use the existing photo app by Tidbyt to display GIFs.

I saved the GIF you linked above to my camera roll and then selected it from within the Tidbyt app. Here's what it looks like:

![IMG_2987](https://user-images.githubusercontent.com/3769813/149641028-cf24f4dc-0fd2-4504-b162-3edd4bbc7735.jpg)
